import Head from "next/head";
import styles from "@/styles/Homepage.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.Homepage}>
        <ul>
          <li>Pane</li>
          <li>Acqua</li>
          <li>Vino</li>
        </ul>
        <a href="asdasdasd">asdasdasd</a>
      </div>
    </>
  );
}
