import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";

const TodoItem = ({ todoData, setIsRendered }) => {
  const onHandleDelete = () => {
    fetch(`/api/todos/${todoData._id}`, {
      method: "DELETE",
      headers: {
        "Content-Type": "application/json",
      },
    });
    setIsRendered((prev) => !prev);
  };

  return (
    <div>
      <p>{todoData.content}</p>
      <input type="checkbox" checked={todoData.completed} />
      <button onClick={onHandleDelete}>❌</button>
    </div>
  );
};

const TodoList = () => {
  const [todos, setTodos] = useState([]);
  const [isRendered, setIsRendered] = useState(false);

  useEffect(() => {
    fetch("/api/todos")
      .then((res) => res.json())
      .then((todos) => setTodos(todos.data));
  }, [isRendered]);

  return (
    <>
      <h1>Lista todos </h1>
      {todos.map((todo) => (
        <TodoItem todoData={todo} key={todo.id} setIsRendered={setIsRendered} />
      ))}
    </>
  );
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <TodoList />
      </main>
    </>
  );
}
